{{- if .Values.metrics.enabled  }}
apiVersion: service-monitors.monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.metadata.names.metrics_name }}
  namespace: {{ .Values.metrics.namespace }}
  labels: {{ .Values.metrics.label }}
  annotations: {}
spec:
  {{- if .Values.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.metrics.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
  {{- if .Values.metrics.selector}}
    matchLabels: {{ .Values.serviceMonitor.selector}}
  {{- end}}
  endpoints:
    - port: metrics
      {{- if .Values.metrics.serviceMonitor.interval }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- toYaml .Values.metrics.serviceMonitor.metricRelabelings | nindent 6 }}
      {{- end }}
  
{{- end }}
