apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cass-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: "local-path"

