{{- if ( .Values.dbUser.condition) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.names.fullname}}
  namespace: {{ .Values.metadata.names.namespace }}
type: Opaque
data:
  cassandra-username: {{ .Values.dbUser.user | b64enc | quote }}
  cassandra-password: {{ include "cassandra.password" . | b64enc | quote }}
{{- end}}