{{- if (not .Values.dbUser.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.names.fullname}}
  namespace: {{ .Values.metadata.release.namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
{{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  cassandra-password: {{ include "cassandra.password" . | b64enc | quote }}
{{- end}}