apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.metadata.names.namespace}}
  name: {{ .Values.metadata.names.fullname}}
  labels: 
    app: {{ .Values.metadata.labels.app}}
  
spec:
  clusterIP: None
  type: {{ .Values.services.type }}  
  {{- if and (eq .Values.services.type "LoadBalancer") (not (empty .Values.services.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.services.loadBalancerIP }}
  {{- end }}
  {{- if .Values.services.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml .Values.services.loadBalancerSourceRanges | nindent 4 }} 
  {{- end}}
  {{- if .Values.services.clusterIP }}
  clusterIP: {{ .Values.services.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.services.type "LoadBalancer") (eq .Values.services.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.services.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
  - name: {{ .Values.services.cql.name}}
    port: {{ .Values.containerPorts.cql}}
    nodePort: {{ .Values.services.cql.nodePort}}            
  - name: {{ .Values.services.metrics.name}}
    port: {{ .Values.metrics.containerPorts.http}}
    nodePort: {{ .Values.services.metrics.nodePort}}            

